version: 0.2

phases:
  build:
    commands:
      - echo Entered the build Phase....
      - mvn clean package
    
  post_build:
    commands:
    - echo Build Completed Successfully
    
artifacts:
  files:
    - target/order-service-0.0.1-SNAPSHOT.jar
  discard-paths: yes    